micronaut:
  application:
    name: r2dbcDemo
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/postgres
      username: admin
      password: password
#      schema-generate: CREATE_DROP
      dialect: POSTGRES
